### PR TITLE
[BUGFIX] Make the Composer scripts independent of the working directory

### LINKED ISSUE #23: `composer create-project` fails with "No such file or directory"
#### Short description

While installing the base distribution using the supplied instructions, the following error occurs:

```bash
$ composer create-project -s dev --no-dev phplist/base-distribution your-project
> cp -rf vendor/phplist/phplist4-core/web/ .
cp: cannot stat 'vendor/phplist/phplist4-core/web/': No such file or directory
Script cp -rf vendor/phplist/phplist4-core/web/ . handling the document-root event returned with error code 1
```

#### PHP and Composer version
Composer version 1.5-dev (27ee47def7648652615979e504d6bcc2e7f4bdef) 2017-05-31 14:05:54
PHP 7.1.7 (cli) (built: Jul  6 2017 12:10:54) ( NTS )

### PR DESCRIPTION
**Pull request by oliverklee**
This allows the scripts to work correctly e.g., when running
composer create-project.

Fixes #23

### CODE REVIEW

**Comment by oliverklee** [comment]
AFAIK, we can only test the post-root-package-install after this has been merged.

File: Classes/Composer/ScriptHandler.php [hunk 1]
```diff
@@ -0,0 +1,57 @@
+<?php
+declare(strict_types=1);
+
+namespace PhpList\BaseDistribution\Composer;
+
+use Symfony\Component\Filesystem\Exception\IOException;
+use Symfony\Component\Filesystem\Filesystem;
+
+/**
+ * This class provides Composer-related tasks.
```
Comment (samtuke) [inline Classes/Composer/ScriptHandler.php]: Suggested clarification: "This class provides Composer-related functionality for setting up and managing phpList modules"

Comment (oliverklee) [reply Classes/Composer/ScriptHandler.php]: changed and repushed

**Review by samtuke — APPROVED** [review]
